#! /bin/bash

######################################################################################################
### Making genotyping array file for kinship matrices in SAIGE-GENE+, fastGWA and BOLT-LMM
######################################################################################################
### For all analyses that used mixed-effects models, the genotyping array data were used for computing 
### the genetic relatedness matrices. Same pruning was used across SAIGE-GENE+, fastGWA and BOLT-LMM. 
### Of note: the software packages variably applied (standard) internal QC too, meaning that
### variant numbers for the final matrices differed very slightly by software/trait.

# Analyses were run in Swiss Army Knife

mkdir tmp/
cd tmp/

echo "READING IN INPUT FILES"
# Import genotyping array files
dx download ${PROJECT}:path/to/bed/ukb_cal_chr${chr}_v2.bed # genotyping array bed file 
dx download ${PROJECT}:path/to/bim/ukb_cal_chr${chr}_v2.bim # genotyping array bim file 
dx download ${PROJECT}:path/to/fam/ukb708_cal_chr${chr}_v2_s488374.fam # genotyping array fam file 

# Import text file with genotype variants passing initial variant QC 
dx download ${PROJECT}:path/to/QCd_SNPlist/array_snps_pass.snplist

# Import double-column (IID, FID) file with IDs of samples passing all exome sequencing and genotyping array QC for the initial 200k subset of UKB exomes.
dx download ${PROJECT}:path/to/QC_passingIDs/ids_double_afterQC_sekIDs.txt

# Extracting passing variants and samples
for chr in {1..22};
  do plink2 \
  --bed ukb_cal_chr${chr}_v2.bed \ 
  --bim ukb_snp_chr${chr}_v2.bim \ 
  --fam ukb708_cal_chr${chr}_v2_s488374.fam \ 
  --keep ids_double_afterQC_sekIDs.txt \ # text file (IDs and FIDs) with samples passing all exome and array QC and within the initial 200k UKB release
  --extract array_snps_pass.snplist \ # text file with variant IDs that pass QC
  --make-bed \
  --out ukbb200k_array_chr${chr}_inter1 &
done

# LD pruning variants 
for chr in {1..22};
  # LD prune for GRM
   plink2 \
   --bfile ukbb200k_array_chr${chr}_inter1 \
   --indep-pairwise 500 50 0.2 \
   --out plink2_chr${chr} &
done

for chr in {1..22};
  plink2 \
  --bfile ukbb200k_array_chr${chr}_inter1 \
  --make-bed \
  --exclude plink2_chr${chr}.prune.out \
  --out ukbb200k_array_chr${chr}_pruned &
done 

# Merging chromosomes into one file
touch list_beds.txt
for chr in {2..22}
do
  echo ukbb200k_array_chr${chr}_pruned.bed" "ukbb200k_array_chr${chr}_pruned.bim" "ukbb200k_array_chr${chr}_pruned.fam >> list_beds.txt
done

plink \
--bed ukbb200k_array_chr1_pruned.bed \
--bim ukbb200k_array_chr1_pruned.bim \
--fam ukbb200k_array_chr1_pruned.fam \
--merge-list list_beds.txt \
--keep-allele-order \
--make-bed \
--out ../ukbb200k_array_chrall.*

cd ..
rm -rf tmp/

echo UPLOADING FILES
# When using Swiss Army Knife output files (in this case ukbb200k_array_chrall.bed, ukbb200k_array_chrall.bim and ukbb200k_array_chrall.fam) will automatically be moved to the 'destination' directory
