#! /bin/bash

######################################################################################################
### Making genotyping array file for kinship matrices in SAIGE-GENE+, fastGWA and BOLT-LMM
######################################################################################################
### For all analyses that used mixed-effects models, the genotyping array data were used for computing 
### the genetic relatedness matrices. Same pruning was used across SAIGE-GENE+, fastGWA and BOLT-LMM. 
### Of note: the software packages variably applied (standard) internal QC too, meaning that
### variant numbers for the final matrices differed very slightly by software/trait.

# Analyses were run in Swiss Army Knife

for chr in {1..22};
  do plink2 \
  --bed /mnt/project/path/to/bed/ukb_cal_chr${chr}_v2.bed \ # genotyping array bed file 
  --bim /mnt/project/path/to/bim/ukb_snp_chr${chr}_v2.bim \ # genotyping array bim file 
  --fam /mnt/project/path/to/fam/ukb708_cal_chr${chr}_v2_s488374.fam \ # genotyping array fam file 
  --keep /mnt/project/path/to/QC_passingIDs/ids_double_afterQC_sekIDs.txt \ # text file (IDs and FIDs) with samples passing all exome and array QC and within the initial 200k UKB release
  --extract /mnt/project/path/to/QCd_SNPlist/array_snps_pass.snplist \ # text file with variant IDs that pass QC
  --make-bed \
  --out ukbb200k_array_chr${chr}_inter1 &
done

for chr in {1..22};
  # LD prune for GRM
   plink2 \
   --bfile ukbb200k_array_chr${chr}_inter1 \
   --indep-pairwise 500 50 0.2 \
   --out plink2_chr${chr} &
done
  
for chr in {1..22};
  plink2 \
  --bfile ukbb200k_array_chr${chr}_inter1 \
  --make-bed \
  --exclude plink2_chr${chr}.prune.out \
  --out ukbb200k_array_chr${chr}_pruned &
done 
